version: '2'

services:
  app:
    image: 'callista:checkpoint'
    container_name: app
    privileged: true
    cap_add:
      - CHECKPOINT_RESTORE
      - SYS_ADMIN
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/database
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver

  db:
    image: 'postgres:16.0-alpine'
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - '5432:5432'
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d